version: '3.1'

services:
  mongodb-database:
    image: mongo
    container_name: b42_mongodb
    command: mongod --port 27018
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 27018:27018
